# Generated by Django 3.0.11 on 2021-04-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
    ]
